app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/curious_db
    username: alpha-n1khil
    password: 123456
    pool-size: 30

spring:
  flyway:
    baseline-on-migrate: true  # SET TO `true`, cuz database already has some table data.
    enabled: false

server:
  servlet:
    session:
      cookie:
        max-age: 604800